chore: more minor fixes following qa of feat/build-pypi-package

diff --git a/.github/workflows/deploy_to_pypi.yaml b/.github/workflows/deploy_to_pypi.yaml
--- a/.github/workflows/deploy_to_pypi.yaml
+++ b/.github/workflows/deploy_to_pypi.yaml
@@ -17,7 +17,10 @@ jobs:
       attestations: write
       id-token: write
     # only allow tagged commits to be deployed
-    if: startsWith(github.ref, "refs/tags")
+    if: ${{ !startsWith(github.ref, "refs/tags") }}
+    run: |
+      echo "ERROR: You can only deploy a tagged commit to PyPI."
+      exit 1
     steps:
       - name: Check out repository
         id: build-repo-checkout
